// @generated by `cargo xtask gen-api` — DO NOT EDIT.
// Source of truth: the `api-schema` Rust crate. Re-run the command after
// changing it, and commit the result.

import type { AppVersion, DmlRequest, DmlResult, Keybinding, KeybindingDeleteParams, Preset, PresetDeleteParams, PresetUpdateParams, Query, QueryDeleteParams, QueryRecordPlayParams, QueryRenameParams, QueryUpdateDefinitionParams } from "./types";
import { rpcCall } from "./rpc";

export async function queryList(): Promise<Query[]> {
  return (await rpcCall("query.list", null)) as Query[];
}

export async function queryAdd(params: Query): Promise<null> {
  return (await rpcCall("query.add", params)) as null;
}

export async function queryDelete(params: QueryDeleteParams): Promise<null> {
  return (await rpcCall("query.delete", params)) as null;
}

export async function queryRecordPlay(params: QueryRecordPlayParams): Promise<null> {
  return (await rpcCall("query.record_play", params)) as null;
}

export async function queryRename(params: QueryRenameParams): Promise<null> {
  return (await rpcCall("query.rename", params)) as null;
}

export async function queryUpdateDefinition(params: QueryUpdateDefinitionParams): Promise<null> {
  return (await rpcCall("query.update_definition", params)) as null;
}

export async function presetList(): Promise<Preset[]> {
  return (await rpcCall("preset.list", null)) as Preset[];
}

export async function presetAdd(params: Preset): Promise<null> {
  return (await rpcCall("preset.add", params)) as null;
}

export async function presetUpdate(params: PresetUpdateParams): Promise<null> {
  return (await rpcCall("preset.update", params)) as null;
}

export async function presetDelete(params: PresetDeleteParams): Promise<null> {
  return (await rpcCall("preset.delete", params)) as null;
}

export async function keybindingList(): Promise<Keybinding[]> {
  return (await rpcCall("keybinding.list", null)) as Keybinding[];
}

export async function keybindingSet(params: Keybinding): Promise<null> {
  return (await rpcCall("keybinding.set", params)) as null;
}

export async function keybindingDelete(params: KeybindingDeleteParams): Promise<null> {
  return (await rpcCall("keybinding.delete", params)) as null;
}

export async function dml(params: DmlRequest): Promise<DmlResult> {
  return (await rpcCall("dml", params)) as DmlResult;
}

export async function appVersion(): Promise<AppVersion> {
  return (await rpcCall("app.version", null)) as AppVersion;
}

// --- Non-RPC transports -----------------------------------------------------

/**
 * POSTs a raw SQL string to `/api/query` and returns the Arrow IPC response
 * bytes. Decoding (via apache-arrow) stays in the frontend. Throws on a non-2xx
 * response (a bad SQL string returns 400 + a plain-text DuckDB error).
 */
export async function postQuery(sql: string): Promise<ArrayBuffer> {
  const res = await fetch("/api/query", {
    method: "POST",
    headers: { "content-type": "text/plain" },
    body: sql,
  });
  if (!res.ok) throw new Error(`${res.status} ${await res.text()}`);
  return res.arrayBuffer();
}

/**
 * The streaming-audio URL for a track id (`GET /api/tracks/{id}/stream`).
 * `quality` mirrors the backend's `StreamParams.quality`: omit it (or pass
 * "original") to stream the source file as-is; pass "opus128" to request
 * the low-bandwidth transcode (the server only transcodes lossless sources —
 * a lossy file streams unchanged either way).
 */
export function trackStreamUrl(id: string, quality?: string): string {
  const q = quality ? `?quality=${encodeURIComponent(quality)}` : "";
  return `/api/tracks/${encodeURIComponent(id)}/stream${q}`;
}
