// @generated by `cargo xtask gen-api` — DO NOT EDIT.
// Source of truth: the `api-schema` Rust crate. Re-run the command after
// changing it, and commit the result.

/** The `error` object of a failed JSON-RPC response. */
export interface RpcError {
  code: number;
  message: string;
  data?: unknown;
}

interface RpcEnvelope {
  result?: unknown;
  error?: RpcError;
  id: number;
}

let nextId = 1;

/**
 * POSTs a single JSON-RPC 2.0 call to `/api/rpc` and returns its result. The wire
 * is already camelCase (the server renames via serde), so callers can cast the
 * result to the generated type directly. Same-origin in production; in dev Vite
 * proxies `/api` to the backend. Throws on a transport error or an RPC `error`.
 */
export async function rpcCall(
  method: string,
  params: unknown = null,
): Promise<unknown> {
  const res = await fetch("/api/rpc", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ jsonrpc: "2.0", method, params, id: nextId++ }),
  });
  if (!res.ok) throw new Error(`${res.status} ${await res.text()}`);
  const env = (await res.json()) as RpcEnvelope;
  if (env.error) throw new Error(env.error.message ?? "rpc error");
  return env.result ?? null;
}
