// @generated by `cargo xtask gen-api` — DO NOT EDIT.
// Source of truth: the `api-schema` Rust crate. Re-run the command after
// changing it, and commit the result.

export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key: string]: JsonValue };

/**
 * A single DML operation. The `values` and `where` maps are keyed by *database
 * column names* and are sent verbatim — serde's `rename_all` on the server only
 * touches declared struct fields, never these free-form map keys.
 */
export type DmlOperation =
  | {
      operation: "insert";
      id: string;
      table: string;
      values: Record<string, JsonValue>;
    }
  | {
      operation: "update";
      id: string;
      table: string;
      where: Record<string, JsonValue>;
      values: Record<string, JsonValue>;
    }
  | {
      operation: "delete";
      id: string;
      table: string;
      where: Record<string, JsonValue>;
    };

export type DmlRequest = { operations: DmlOperation[] };

/** Per-operation returned rows, keyed by operation id (delete ops produce none). */
export type DmlResult = Record<string, Record<string, JsonValue>>;

export type SourceKind = "query" | "playlist";

export type Source = { id: string, kind: SourceKind, name: string, createdAt: number, modifiedAt: number, lastPlay: number, definition: string, parent: string | null, position: number, queryId: string | null, playlistId: string | null, };

export type SourceFolder = { id: string, name: string, parent: string | null, position: number, };

export type TreeItemKind = "source" | "folder";

export type Placement = { kind: TreeItemKind, id: string, parent: string | null, position: number, };

export type Preset = { id: string, name: string, baseTable: string, section: string, definition: string, isDefault: boolean, createdAt: number, modifiedAt: number, };

export type Keybinding = { commandId: string, chord: string | null, };

export type Setting = { key: string, value: string, };

export type AppVersion = { buildId: string, serverVersion: string, };

export type QueryDeleteParams = { id: string, };

export type SourceRecordPlayParams = { id: string, lastPlay: number, };

export type SourceRenameParams = { id: string, name: string, };

export type SourceUpdateDefinitionParams = { id: string, definition: string, modifiedAt: number, };

export type SourceArrangeParams = { placements: Array<Placement>, };

export type FolderRenameParams = { id: string, name: string, };

export type FolderDeleteParams = { id: string, };

export type PresetUpdateParams = { id: string, name: string, definition: string, isDefault: boolean, modifiedAt: number, };

export type PresetDeleteParams = { id: string, };

export type KeybindingDeleteParams = { commandId: string, };

export type SettingDeleteParams = { key: string, };
