//! `cargo xtask gen-api`: regenerate the TypeScript API client under
//! `api-client/` from the shared [`api_schema`] contract.
//!
//! The client is the single consumer-facing surface for `POST /api/rpc` (plus
//! the two non-RPC transports, `POST /api/query` and the track-stream URL). Every
//! wire type comes from `api-schema`'s `ts-rs` derives, so this command only
//! stitches those declarations together with the hand-written transport and the
//! per-method client functions. Casing is handled on the server (serde
//! `rename_all`), so the client does no conversion. Re-running it is idempotent.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::Path;

use api_schema::{METHODS, type_decls};

const BANNER: &str = "\
// @generated by `cargo xtask gen-api` — DO NOT EDIT.
// Source of truth: the `api-schema` Rust crate. Re-run the command after
// changing it, and commit the result.
";

pub(crate) fn generate(root: &Path) -> Result<(), String> {
    let out = root.join("api-client/src");
    std::fs::create_dir_all(&out).map_err(|e| format!("creating {}: {e}", out.display()))?;

    write(&out, "types.ts", &types_ts())?;
    write(&out, "rpc.ts", &rpc_ts())?;
    write(&out, "client.ts", &client_ts())?;
    write(&out, "index.ts", &index_ts())?;

    println!("Generated TypeScript client in {}", out.display());
    Ok(())
}

fn write(dir: &Path, name: &str, contents: &str) -> Result<(), String> {
    let path = dir.join(name);
    std::fs::write(&path, contents).map_err(|e| format!("writing {}: {e}", path.display()))
}

/// The type module: a static preamble (`JsonValue` + the DML types) then every
/// `ts-rs`-derived declaration.
fn types_ts() -> String {
    let dml = "\
export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key: string]: JsonValue };

/**
 * A single DML operation. The `values` and `where` maps are keyed by *database
 * column names* and are sent verbatim — serde's `rename_all` on the server only
 * touches declared struct fields, never these free-form map keys.
 */
export type DmlOperation =
  | {
      operation: \"insert\";
      id: string;
      table: string;
      values: Record<string, JsonValue>;
    }
  | {
      operation: \"update\";
      id: string;
      table: string;
      where: Record<string, JsonValue>;
      values: Record<string, JsonValue>;
    }
  | {
      operation: \"delete\";
      id: string;
      table: string;
      where: Record<string, JsonValue>;
    };

export type DmlRequest = { operations: DmlOperation[] };

/** Per-operation returned rows, keyed by operation id (delete ops produce none). */
export type DmlResult = Record<string, Record<string, JsonValue>>;";

    format!("{BANNER}\n{dml}\n\n{}\n", type_decls().join("\n\n"))
}

/// The JSON-RPC transport, ported from the retired hand-written shim.
fn rpc_ts() -> String {
    let body = "\
/** The `error` object of a failed JSON-RPC response. */
export interface RpcError {
  code: number;
  message: string;
  data?: unknown;
}

interface RpcEnvelope {
  result?: unknown;
  error?: RpcError;
  id: number;
}

let nextId = 1;

/**
 * POSTs a single JSON-RPC 2.0 call to `/api/rpc` and returns its result. The wire
 * is already camelCase (the server renames via serde), so callers can cast the
 * result to the generated type directly. Same-origin in production; in dev Vite
 * proxies `/api` to the backend. Throws on a transport error or an RPC `error`.
 */
export async function rpcCall(
  method: string,
  params: unknown = null,
): Promise<unknown> {
  const res = await fetch(\"/api/rpc\", {
    method: \"POST\",
    headers: { \"content-type\": \"application/json\" },
    body: JSON.stringify({ jsonrpc: \"2.0\", method, params, id: nextId++ }),
  });
  if (!res.ok) throw new Error(`${res.status} ${await res.text()}`);
  const env = (await res.json()) as RpcEnvelope;
  if (env.error) throw new Error(env.error.message ?? \"rpc error\");
  return env.result ?? null;
}";
    format!("{BANNER}\n{body}\n")
}

/// The per-method client functions plus the two non-RPC transports.
fn client_ts() -> String {
    // The set of type names to import from `./types`: every params type and the
    // base of every result type (`Query[]` → `Query`), minus `null`.
    let mut used: BTreeSet<&str> = BTreeSet::new();
    for m in METHODS {
        if let Some(p) = m.params {
            used.insert(p);
        }
        let base = m.result.trim_end_matches("[]");
        if base != "null" {
            used.insert(base);
        }
    }
    let imports = used.into_iter().collect::<Vec<_>>().join(", ");

    let mut fns = String::new();
    for m in METHODS {
        let sig_param = m.params.map_or(String::new(), |p| format!("params: {p}"));
        // The params argument passed to `rpcCall` (the wire is already camelCase,
        // so params go over as-is; no-arg methods send `null`).
        let arg = if m.params.is_some() { "params" } else { "null" };
        let _ = write!(
            fns,
            "export async function {func}({sig_param}): Promise<{result}> {{\n  return (await rpcCall(\"{wire}\", {arg})) as {result};\n}}\n\n",
            func = m.func,
            wire = m.wire,
            result = m.result,
        );
    }

    let transports = "\
// --- Non-RPC transports -----------------------------------------------------

/**
 * POSTs a raw SQL string to `/api/query` and returns the Arrow IPC response
 * bytes. Decoding (via apache-arrow) stays in the frontend. Throws on a non-2xx
 * response (a bad SQL string returns 400 + a plain-text DuckDB error).
 */
export async function postQuery(sql: string): Promise<ArrayBuffer> {
  const res = await fetch(\"/api/query\", {
    method: \"POST\",
    headers: { \"content-type\": \"text/plain\" },
    body: sql,
  });
  if (!res.ok) throw new Error(`${res.status} ${await res.text()}`);
  return res.arrayBuffer();
}

/**
 * The streaming-audio URL for a track id (`GET /api/tracks/{id}/stream`).
 * `quality` mirrors the backend's `StreamParams.quality`: omit it (or pass
 * \"original\") to stream the source file as-is; pass \"opus128\" to request
 * the low-bandwidth transcode (the server only transcodes lossless sources —
 * a lossy file streams unchanged either way).
 */
export function trackStreamUrl(id: string, quality?: string): string {
  const q = quality ? `?quality=${encodeURIComponent(quality)}` : \"\";
  return `/api/tracks/${encodeURIComponent(id)}/stream${q}`;
}";

    format!(
        "{BANNER}\nimport type {{ {imports} }} from \"./types\";\nimport {{ rpcCall }} from \"./rpc\";\n\n{fns}{transports}\n"
    )
}

fn index_ts() -> String {
    let body = "\
export * from \"./types\";
export * from \"./client\";
export type { RpcError } from \"./rpc\";";
    format!("{BANNER}\n{body}\n")
}
